### ISSUE TITLE
`httpx.HTTPStatusError: Client error '401 Unauthorized'` error when authorizing

### ISSUE THREAD

**Issue by EthanMarx** [kr8s-org/kr8s#214] opened 2023-11-21 18:27 UTC
### Which project are you reporting a bug for?

kr8s

### What happened?

Hello!

I have been running into an issue where simple use of `kr8s`, e.g.
```python
import kr8s
api = kr8s.api(kubeconfig="~/.kube/config")
kr8s.get("pods", api=api, namespace="bbhnet")
```

gives the following error
```
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://67.58.53.147:6443/api/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

However, the equivalent `kubectl` command runs just fine:
```
kubectl get pods
```

Additionally, the error will suddenly go away after some time after repeated calls to the above snippet. 

Any help will be appreciated!

**Comment by jacobtomlinson** [comment] 2023-11-21 21:35
Could you share the output of `kubectl config view` (please ensure all the secrets are removed)?

**Comment by EthanMarx** [comment] 2023-11-21 22:21
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://67.58.53.147:6443
  name: nautilus
contexts:
- context:
    cluster: nautilus
    namespace: bbhnet
    user: http://cilogon.org/serverA/users/93606
  name: nautilus
current-context: nautilus
kind: Config
preferences: {}
users:
- name: http://cilogon.org/serverA/users/93606
  user:
    auth-provider:
      config:
        client-id: 
        client-secret: 
        id-token: 
        idp-issuer-url: https://cilogon.org
        refresh-token: NB2HI4DTHIXS6Y3JNRXWO33OFZXXEZZPN5QXK5DIGIXTIZTFMEZGENZRMY4DOY3FMIYDMZBSMYYTENBTGE4GENJUGA2TSNB7OR4XAZJ5OJSWM4TFONUFI33LMVXCM5DTHUYTOMBQGU4TSMZYGA2TSOJGOZSXE43JN5XD25RSFYYCM3DJMZSXI2LNMU6TENJZGIYDAMBQGAYA
      name: oidc
```

**Comment by jacobtomlinson** [comment] 2023-11-22 11:31
Thanks that's helpful.

I'm guess this is related to the fact that we don't currently refresh OIDC tokens automatically.

https://github.com/kr8s-org/kr8s/blob/ec997ce0e01c59309d89f55b90b00b50493ac5c1/kr8s/_auth.py#L197

I assume the following steps will happen if you try them:
- Wait some amount of time for your OIDC token to expire
- Run a `kr8s` command and reproduce the 401 error
- Run any `kubectl` command which will refresh the token
- Run a `kr8s` command again and it will succeed

Would you mind giving these steps a go to verify that this is the problem?

**Comment by jacobtomlinson** [comment] 2023-11-22 14:34
I guess it depends on what you're working on. I can't think of a quick way to patch in a token refresh. But here are a few hacky options while I get the token refreshing working.

You could ensure your token gets refreshed before you do anything with kr8s. But of course, if your program runs longer than the token expiry then this wont work.

```python
import kr8s
import subprocess

# Make a small request with kubectl to ensure you have a refreshed token
subprocess.run(["kubectl", "cluster-info"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

# Use kr8s
api = kr8s.api(kubeconfig="~/.kube/config")
kr8s.get("pods", api=api, namespace="bbhnet")
```

You could also try using a retry library like [tenacity](https://tenacity.readthedocs.io/en/latest/).

```python
import kr8s
import subprocess
from tenacity import retry

def refresh_token(*args, **kwargs):
    subprocess.run(["kubectl", "cluster-info"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

@retry(after=refresh_token)
def main():
    api = kr8s.api(kubeconfig="~/.kube/config")
    kr8s.get("pods", api=api, namespace="bbhnet")

main()
```

**Comment by jacobtomlinson** [comment] 2023-11-22 14:41
I'm going to close this out now as a duplicate of #125 and add some priority to that issue.

**Closed by jacobtomlinson** 2023-11-22 14:41 UTC
Labels: bug, kr8s, auth, auth/oidc

**Comment by jacobtomlinson** [comment] 2023-11-22 14:58
When auth fails we retry a couple of times. I wonder if a more robust hacky workaround could be to patch in something like this.

```python
import kr8s
import subprocess

async def reauthenticate_oidc(self):
    """Replacement reauthenticate method that uses kubectl to refresh the OIDC token."""
    subprocess.run(["kubectl", "cluster-info"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    await self._load_kubeconfig()

api = kr8s.api(kubeconfig="~/.kube/config")
# Monkey patch in the new reauthenticate method
api.auth.reauthenticate = reauthenticate_oidc.__get__(api.auth, type(api.auth))

kr8s.get("pods", api=api, namespace="bbhnet")
```
